Comment Java version required for monkeyrunner
Symptom:
```
-Djava.ext.dirs=... is not supported.  Use -classpath instead.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

See also https://docs.oracle.com/javase/10/migrate/toc.htm