Enable calling POSIX script to forward positional parameters
... without losing splitting by assigning to string.

Symptom (shellcheck warning):
```
In /home/travis/build/lucafavatella/provisioning-osx/bin/brew line 17:
P="$@"
  ^--^ SC2124: Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.
```

Bug:
```
$ brew info 'a b'
Error: No available formula with the name "a"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.

Error: No available formula with the name "b"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
```
... now fixed:
```
$ brew info 'a b'
Error: No available formula with the name "a b"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
```